### PR TITLE
Extend to cover more python 3 versions

### PR DESCRIPTION
**Pull request by tacaswell**
This PR generalizes a bit to cover more python 3 version.  Probably can re-arrange where the loop over python minor version happens to be more efficient.

 - Rather than hard-coding the patch versions, generated them up to X.Y.14 (to match the highest 2.7).  Might be better to scrape https://www.python.org/doc/versions/ but :man_shrugging: 
 - use `pathlib` :smile: 
 - pep8 cleanups

Current output:

```
12:38 $ python -m py_versions_and_distros
abuledu 15.08-beta: Python 3.4.0
antix 16.2: Python 3.4.2
antix 15: Python 3.4.2
apodio 10.03: Python 3.4.0
avlinux 2017.4.9: Python 3.4.4
avlinux 2016.8.30: Python 3.4.4
backbox 4.7: Python 3.4.0
berry 1.22: Python 3.4.3
bicom 4.1.2-r2: Python 3.4.3
biolinux 8.0.7: Python 3.4.0
bitkey 14.2.0: Python 3.4.2
blacklab 7.7: Python 3.4.0
blackarch 2015.03.29: Python 3.4.3
boss 6.1: Python 3.4.2
bunsenlabs hydrogen: Python 3.4.2
caine 7.0: Python 3.4.0
caine 6.0: Python 3.4.0
calculate 17.6: Python 3.4.5
calculate 15.17: Python 3.4.3
calculate 14.16.2: Python 3.4.1
canaima 5.0-beta3: Python 3.4.2
chakra 2016.02: Python 3.4.3
chakra 2015.11: Python 3.4.3
chapeau 23: Python 3.4.3
chapeau 22: Python 3.4.2
debian unstable: Python 3.4.2
skolelinux 8: Python 3.4.2
deepin 2014.3: Python 3.4.0
deft 2017.1: Python 3.4.0
devuan 1.0.0: Python 3.4.2
duzeru 2.4: Python 3.4.2
easynas 0.6.2: Python 3.4.1
edubuntu 14.04: Python 3.4.0
elementary 0.3.2: Python 3.4.3
emmabuntus 3-1.04: Python 3.4.0
extix 15.4: Python 3.4.3
funtoo current: Python 3.4.5
gecko 421.160511.0: Python 3.4.1
gentoo stable: Python 3.4.5
gentoo 20160514: Python 3.4.3
greenie 14.04.5: Python 3.4.0
grml 2014.11: Python 3.4.2
kaiana 14.04: Python 3.4.0
kali 2.0: Python 3.4.2
kaos 2015.11: Python 3.4.3
karoshi 10.1.2: Python 3.4.0
knoppix 7.6.1: Python 3.4.3
kodachi 3.7: Python 3.4.2
kxstudio 14.04.5: Python 3.4.0
linuxfx 7.4.2: Python 3.4.0
lite 2.8: Python 3.4.0
lliurex 15.05: Python 3.4.0
luninux 15.10: Python 3.4.3
lxle 14.04.4: Python 3.4.0
mageia 5.1: Python 3.4.3
makulu 10: Python 3.4.3
makulu 7.0: Python 3.4.0
makulu 6.1: Python 3.4.1
mangaka mou: Python 3.4.0
max 8.0: Python 3.4.0
metamorphose 7.1.8: Python 3.4.2
minino 2017: Python 3.4.1
minino 3.0: Python 3.4.2
mint 17.3: Python 3.4.3
mx 16.1: Python 3.4.2
netrunner 16: Python 3.4.3
netrunner 14.1: Python 3.4.0
nixos 17.09: Python 3.4.7
nixos 16.09: Python 3.4.5
nixos 16.03: Python 3.4.4
nst 22-7334: Python 3.4.2
ob2d 1.0.0: Python 3.4.2
openbsd 6.1: Python 3.4.5
openbsd 6.0: Python 3.4.5
openmandriva 3.02: Python 3.4.4
opensuse 42.3: Python 3.4.6
opensuse 42.2: Python 3.4.5
pardustopluluk 3.0: Python 3.4.2
parrotsecurity 3.0.1: Python 3.4.4
parsix 8.15r1: Python 3.4.2
parsix 8.10r0: Python 3.4.2
parsix 8.5r1: Python 3.4.2
pclinuxos apt: Python 3.4.3
pclinuxos 2017.07: Python 3.4.3
pclinuxos 2016.03: Python 3.4.3
peachosi 14.04.01.36: Python 3.4.0
pelicanhpc 4.1: Python 3.4.2
pentoo 2015.0-rc5: Python 3.4.3
peppermint 6: Python 3.4.0
pisi 1.2: Python 3.4.1
pisi 1.1: Python 3.4.1
point 3.2: Python 3.4.2
poliarch 15.04: Python 3.4.3
poliarch 14.10: Python 3.4.2
primtux 2: Python 3.4.2
primtux eiffel: Python 3.4.2
proxmox 4.3: Python 3.4.2
q4os 1.8.8: Python 3.4.2
qubes 3.2: Python 3.4.3
raspbian 2017-07-05: Python 3.4.2
redcore 1708: Python 3.4.5
refracta 8.3-20170305: Python 3.4.2
rescatux 0.41-beta1: Python 3.4.2
resulinux 5.0-beta2: Python 3.4.2
robolinux 8.8.1: Python 3.4.2
rosa r8: Python 3.4.5
rosa r7: Python 3.4.3
runtu 14.04.2: Python 3.4.0
sabayon 16.11: Python 3.4.3
sabayon 15.12: Python 3.4.3
salentos 1.0.1: Python 3.4.2
salentos 14.04.2: Python 3.4.0
semplice 2015.1-preview: Python 3.4.2
semplice 7.0.1: Python 3.4.2
siduction 15.1.0-dev: Python 3.4.3
solydxk 201701: Python 3.4.2
solydxk 201606: Python 3.4.2
sonar 2014.1: Python 3.4.1
star 1.0.1: Python 3.4.2
steamos 2.121: Python 3.4.2
sle 12-sp3: Python 3.4.6
swecha 2016: Python 3.4.0
swift 16: Python 3.4.2
systemrescue 5.1.0: Python 3.4.5
systemrescue 4.9.0: Python 3.4.3
systemrescue 4.6.1: Python 3.4.3
tails 2.12: Python 3.4.2
tanglu 3.0: Python 3.4.2
tanglu 2.0: Python 3.4.1
torios 1.0: Python 3.4.2
trisquel 7.0: Python 3.4.0
uberstudent 4.3: Python 3.4.0
ubuntudp 15.04: Python 3.4.3
ubuntudp 14.04: Python 3.4.0
uhu 3: Python 3.4.1
ulteo 4.0.3: Python 3.4.0
univention 4.2-2: Python 3.4.2
untangle 13.1.0: Python 3.4.2
urix 7.0.3: Python 3.4.1
uruk 1.0: Python 3.4.0
vector 7.2: Python 3.4.3
vinux 5.1: Python 3.4.0
void current: Python 3.4.0
voyager 14.04.04: Python 3.4.0
wattos r9: Python 3.4.0
whonix 13.0.0.1.1: Python 3.4.2
whonix 12.0.0.3.2: Python 3.4.2
wmlive 0.95.7-3: Python 3.4.2
zentyal 4.2: Python 3.4.0
zorin 11: Python 3.4.3
zorin 10: Python 3.4.3
====================================
151 distros with Python 3.4




alt sisyphus: Python 3.5.1
alt 8.1: Python 3.5.1
antergos 2016.11.20: Python 3.5.2
antergos 2015.12.29: Python 3.5.1
antix 17-rc1: Python 3.5.3
apodio 11-beta0.2: Python 3.5.1
arya 2017: Python 3.5.2
avlinux 2017.4.9: Python 3.5.3
avlinux 2016.8.30: Python 3.5.1
backbox 5: Python 3.5.1
backslash olaf: Python 3.5.1
berry 1.24: Python 3.5.2
berry 1.23: Python 3.5.1
blacklab 11.0.1: Python 3.5.1
blacklab 8.2: Python 3.5.1
blackarch 2016.12.29: Python 3.5.2
blackpanther 16.2: Python 3.5.1
blankon 10.0: Python 3.5.1
bluestar 4.8.4: Python 3.5.2
bodhi 4.3.1: Python 3.5.1
caine 8.0: Python 3.5.1
chakra 2017.10: Python 3.5.2
chapeau 24: Python 3.5.1
debian unstable: Python 3.5.4
debian testing: Python 3.5.3
debian 9: Python 3.5.3
skolelinux 9: Python 3.5.3
deepin 15.4.1: Python 3.5.3
deepin 15.3: Python 3.5.1
devuan unstable: Python 3.5.4
devuan testing: Python 3.5.3
elementary 0.4.1: Python 3.5.1
extix 16.5: Python 3.5.1
fedora 25: Python 3.5.2
ferenos 2017.10: Python 3.5.2
ferenos 2016.2: Python 3.5.1
frugalware current: Python 3.5.4
frugalware 2.1: Python 3.5.2
funtoo current: Python 3.5.2
gentoo 20160514: Python 3.5.1
gnustep 2.5.1: Python 3.5.3
greenie 16.04.1: Python 3.5.1
grml 2017.05: Python 3.5.3
kali 2017.2: Python 3.5.3
kali 2016.2: Python 3.5.1
kaos 2016.11: Python 3.5.2
karoshi 11.1: Python 3.5.2
kdeneon 20170907: Python 3.5.1
knoppix 8.1: Python 3.5.3
knoppix 7.7.1: Python 3.5.1
korora 25: Python 3.5.2
korora 24: Python 3.5.1
kubuntu 17.04: Python 3.5.3
kubuntu 16.10: Python 3.5.1
linuxfx 8.0.2: Python 3.5.1
lite 3.6: Python 3.5.1
lliurex 16.06: Python 3.5.1
lubuntu 17.04: Python 3.5.3
lubuntu 16.10: Python 3.5.1
luninux 17.04: Python 3.5.3
luninux 16.04: Python 3.5.1
luninux 15.10: Python 3.5.0
lxle 16.04.2: Python 3.5.1
mageia 6: Python 3.5.3
maui 17.06: Python 3.5.2
maui 2.1: Python 3.5.1
maui 1: Python 3.5.1
max 9.0: Python 3.5.1
metamorphose 8.5.7: Python 3.5.1
metamorphose 8.0.4: Python 3.5.1
mint 18.2: Python 3.5.1
netrunner 17.06: Python 3.5.3
nitrux 1.0.4: Python 3.5.3
nixos 17.09: Python 3.5.4
nixos 16.09: Python 3.5.2
nixos 16.03: Python 3.5.1
nst 24-7977: Python 3.5.1
ob2d 2017-1.1: Python 3.5.3
openbsd 6.1: Python 3.5.2
openbsd 6.0: Python 3.5.2
osgeo 11.0: Python 3.5.1
osgeo 10.5: Python 3.5.1
pardus 17.0: Python 3.5.3
pardustopluluk 4.0: Python 3.5.1
parrotsecurity 3.8: Python 3.5.3
parrotsecurity 3.7: Python 3.5.3
parrotsecurity 3.0.1: Python 3.5.1
peachosi 16.04: Python 3.5.1
pearl 5.0: Python 3.5.2
pearl 4.0: Python 3.5.1
peppermint 8: Python 3.5.1
peppermint 7: Python 3.5.1
poliarch 15.10: Python 3.5.0
porteus 3.2.2: Python 3.5.2
pureos 8.0-beta1: Python 3.5.3
q4os 2.4: Python 3.5.3
qubes 4.0-rc1: Python 3.5.3
raspbian 2017-09-07: Python 3.5.3
rebeccablackos 2016-02-08: Python 3.5.1
rebellin 3.5: Python 3.5.1
rebellin 3.0: Python 3.5.1
rosa r9: Python 3.5.2
runtu 16.04.3: Python 3.5.1
sabayon 17.10: Python 3.5.3
sharklinux 4.10.0: Python 3.5.1
siduction 17.1.0: Python 3.5.3
siduction 16.1.0: Python 3.5.1
solus 3: Python 3.5.4
solus 2017.04.18.0: Python 3.5.2
solus 1.2.1: Python 3.5.2
solydxk 9: Python 3.5.3
sonar 17.01-alpha: Python 3.5.2
sonar 2016.03: Python 3.5.1
sparky 5.0: Python 3.5.3
sparky 4.6.1: Python 3.5.3
sparky 4.5.2: Python 3.5.1
subgraph 2017-09-22-alpha: Python 3.5.3
tails 3.2: Python 3.5.3
tanglu 4.0: Python 3.5.1
trisquel 8.0-alpha: Python 3.5.1
tuxtrans 16.04: Python 3.5.1
ubuntu 17.04: Python 3.5.3
ubuntu 16.10: Python 3.5.1
ubuntubudgie 17.04: Python 3.5.3
ubuntubudgie 16.10: Python 3.5.1
ubuntudp 16.04.1: Python 3.5.1
ubuntugnome 17.04: Python 3.5.3
ubuntugnome 16.10: Python 3.5.1
ubuntugnome 16.04: Python 3.5.1
ubuntukylin 17.04: Python 3.5.3
ubuntukylin 16.10: Python 3.5.1
ubuntumate 17.04: Python 3.5.3
ubuntumate 16.10: Python 3.5.1
ubuntustudio 17.04: Python 3.5.3
ubuntustudio 16.10: Python 3.5.1
ultimate 5.5: Python 3.5.3
ultimate 5.1: Python 3.5.1
ultimate 5.0.1: Python 3.5.1
uruk 2.0-beta2: Python 3.5.1
ututo 2017-rc: Python 3.5.1
voyager 9: Python 3.5.3
voyager 16.04.3: Python 3.5.1
wattos r10: Python 3.5.1
wifislax 4.12: Python 3.5.2
xubuntu 17.04: Python 3.5.3
xubuntu 16.10: Python 3.5.1
zentyal 5.0: Python 3.5.1
zorin 12.2: Python 3.5.1
====================================
148 distros with Python 3.5




antergos 17.10: Python 3.6.2
arch current: Python 3.6.2
archlabs 2017.09: Python 3.6.2
blackarch 2017.08.30: Python 3.6.2
bluestar 4.13.3: Python 3.6.2
cucumber 1.0: Python 3.6.0
debian unstable: Python 3.6.3
debian testing: Python 3.6.2
devuan unstable: Python 3.6.3
extix 17.8: Python 3.6.3
fedora rawhide: Python 3.6.3
fedora 26: Python 3.6.1
funtoo current: Python 3.6.0
gentoo unstable: Python 3.6.3
kali 2017.2: Python 3.6.2
kaos 2017.09: Python 3.6.2
korora 26: Python 3.6.2
kubuntu 17.10-beta2: Python 3.6.2
lfs 8.1-blfs: Python 3.6.2
lubuntu 17.10-beta2: Python 3.6.2
mageia cauldron: Python 3.6.2
manjaro stable: Python 3.6.2
manjaro 17.0.5: Python 3.6.2
nitrux 1.0.4: Python 3.6.2
nixos 17.09: Python 3.6.2
nixos 16.09: Python 3.6.0
nst 26-9267: Python 3.6.2
nutyx packages: Python 3.6.2
openbsd 6.2: Python 3.6.2
openbsd 6.1: Python 3.6.0
parrotsecurity 3.8: Python 3.6.2
parrotsecurity 3.7: Python 3.6.2
pisi 2.0-rc: Python 3.6.0
slackware current: Python 3.6.3
swagarch 17.08: Python 3.6.2
ubuntu snapshot: Python 3.6.3
ubuntubudgie 17.10-beta2: Python 3.6.2
ubuntukylin 17.10-beta2: Python 3.6.2
ubuntumate 17.10-beta2: Python 3.6.2
ubuntustudio 17.10-beta2: Python 3.6.2
void current: Python 3.6.3
xubuntu 17.10-beta2: Python 3.6.2
====================================
42 distros with Python 3.6




====================================
0 distros with Python 3.7




```

### CODE REVIEW

**Comment by hugovk** [comment]
You missed one :)

```bash
[hugo:~/github/python_versions_and_distros] a16df61+ 1 ± pycodestyle .
./__main__.py:5:11: W292 no newline at end of file
```

**Comment by hugovk** [comment]
I get an error running this:
```
[hugo:~/github/python_versions_and_distros] master+* 2m53s 1 ± gco tacaswell/dev
Note: checking out 'tacaswell/dev'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a16df61... DEV: update .gitignore for new output file names
```
```
⌂63% [hugo:~/github/python_versions_and_distros] a16df61+* 1 ± pip3 install -r requirements.txt
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Collecting requests (from -r requirements.txt (line 2))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg (from requests->-r requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg (from requests->-r requirements.txt (line 2))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages/certifi-2017.4.17-py3.6.egg (from requests->-r requirements.txt (line 2))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages/idna-2.5-py3.6.egg (from requests->-r requirements.txt (line 2))
Installing collected packages: beautifulsoup4, requests
Successfully installed beautifulsoup4-4.6.0 requests-2.18.4
```
```
[hugo:~/github/python_versions_and_distros] a16df61+* 1 ± python3 --version
Python 3.6.3
```
```
[hugo:~/github/python_versions_and_distros] a16df61+* ± python3 -m py_versions_and_distros
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 173, in <module>
    main()
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 167, in main
    process_distro(distro)
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 65, in process_distro
    process_resource(distribution, a_elem.text, py_ver)
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 90, in process_resource
    scrape_webpage(resource_url, resource_file_path)
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 30, in scrape_webpage
    fetch_webpage(source_url, destination_filename)
  File "/Users/hugo/github/python_versions_and_distros/py_versions_and_distros.py", line 18, in fetch_webpage
    r = requests.get(source_url)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'https:/distrowatch.com/resource/proxmox/proxmox-5.0.txt': No schema supplied. Perhaps you meant http://https:/distrowatch.com/resource/proxmox/proxmox-5.0.txt?
```

**Comment by tacaswell** [comment]
I may have been over-aggressive with pathification but still working for me because I have already cached the locally....

**Comment by hugovk** [comment]
Great, it's working now!

**Review by Mariatta — APPROVED** [review]
This is great!! Thanks so much @tacaswell!

**Pull request merged**
