### PR TITLE
Update output as of today

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
Note, full output is:
```console
⌂119% [hugo:~/github/python_versions_and_distros] user-agent+* ± python3 -m py_versions_and_distros
abuledu 15.08-beta: Python 3.4.0
antix 16.3: Python 3.4.2
antix 15: Python 3.4.2
apodio 10.03: Python 3.4.0
avlinux 2017.4.9: Python 3.4.4
avlinux 2016.8.30: Python 3.4.4
backbox 4.7: Python 3.4.0
bicom 5.0.0: Python 3.4.3
bicom 4.1.2-r2: Python 3.4.3
biolinux 8.0.8: Python 3.4.0
bitkey 14.2.0: Python 3.4.2
blackarch 2015.03.29: Python 3.4.3
boss 6.1: Python 3.4.2
bunsenlabs 20170429: Python 3.4.2
bunsenlabs 20160710: Python 3.4.2
caine 7.0: Python 3.4.0
calculate 15.17: Python 3.4.3
calculate 14.16.2: Python 3.4.1
canaima 5.0-beta3: Python 3.4.2
chakra 2016.02: Python 3.4.3
chakra 2015.11: Python 3.4.3
chaletos 14.04.3: Python 3.4.0
chapeau 23: Python 3.4.3
chapeau 22: Python 3.4.2
debian unstable: Python 3.4.2
skolelinux 8: Python 3.4.2
deepin 2014.3: Python 3.4.0
deft 2017.1: Python 3.4.0
devuan 1.0.0: Python 3.4.2
duzeru 2.4: Python 3.4.2
easynas 0.6.2: Python 3.4.1
edubuntu 14.04: Python 3.4.0
elementary 0.3.2: Python 3.4.3
emmabuntus 8-1.03: Python 3.4.2
emmabuntus 3-1.04: Python 3.4.0
funtoo current: Python 3.4.5
gecko 423: Python 3.4.6
gecko 422: Python 3.4.5
gentoo 20160514: Python 3.4.3
greenie 14.04.5: Python 3.4.0
grml 2014.11: Python 3.4.2
guixsd 0.12.0: Python 3.4.5
guixsd 0.9.0: Python 3.4.3
karoshi 10.1.2: Python 3.4.0
knoppix 7.6.1: Python 3.4.3
kodachi 3.7: Python 3.4.2
kxstudio 14.04.5: Python 3.4.0
linuxfx 7.4.2: Python 3.4.0
lite 2.8: Python 3.4.0
lliurex 15.05: Python 3.4.0
luninux 15.10: Python 3.4.3
lxle 14.04.4: Python 3.4.0
mageia 5.1: Python 3.4.3
makulu 10: Python 3.4.3
makulu 7.0: Python 3.4.0
mangaka cho: Python 3.4.4
mangaka mou: Python 3.4.0
max 8.0: Python 3.4.0
metamorphose 7.1.8: Python 3.4.2
minino 2017: Python 3.4.1
minino 3.0: Python 3.4.2
mint 17.3: Python 3.4.3
mx 16.1: Python 3.4.2
netrunner 16: Python 3.4.3
netrunner 14.1: Python 3.4.0
nixos 17.09: Python 3.4.7
nixos 16.09: Python 3.4.5
nixos 16.03: Python 3.4.4
nst 22-7334: Python 3.4.2
ob2d 1.0.0: Python 3.4.2
openbsd 6.1: Python 3.4.5
openbsd 6.0: Python 3.4.5
openmandriva 3.03: Python 3.4.4
openmediavault 3.0.94: Python 3.4.2
opensuse 42.3: Python 3.4.6
opensuse 42.2: Python 3.4.5
pardustopluluk 3.0: Python 3.4.2
parrotsecurity 3.0.1: Python 3.4.4
pclinuxos apt: Python 3.4.3
pclinuxos 2017.11: Python 3.4.3
pclinuxos 2016.03: Python 3.4.3
peachosi 14.04.01.36: Python 3.4.0
pelicanhpc 4.1: Python 3.4.2
pentoo 2015.0-rc5: Python 3.4.3
peppermint 6: Python 3.4.0
pinguy 14.04.5: Python 3.4.3
pisi 1.2: Python 3.4.1
pisi 1.1: Python 3.4.1
point 3.2: Python 3.4.2
primtux 2: Python 3.4.2
primtux eiffel: Python 3.4.2
proxmox 4.4: Python 3.4.2
q4os 1.8.8: Python 3.4.2
qubes 3.2: Python 3.4.3
raspbian 2017-07-05: Python 3.4.2
redcore 1710: Python 3.4.5
refracta 8.3-20170305: Python 3.4.2
rescatux 0.51-beta3: Python 3.4.2
robolinux 8.10: Python 3.4.2
robolinux 8.8.1: Python 3.4.2
rosa r8: Python 3.4.5
runtu 14.04.2: Python 3.4.0
sabayon 16.11: Python 3.4.3
salentos 1.0.1: Python 3.4.2
salentos 14.04.2: Python 3.4.0
solydxk 201701: Python 3.4.2
star 1.0.2: Python 3.4.2
steamos 2.148: Python 3.4.2
steamos 2.117: Python 3.4.2
sle 12-sp3: Python 3.4.6
swecha 2016: Python 3.4.0
swift 16: Python 3.4.2
systemrescue 4.9.0: Python 3.4.3
tails 2.12: Python 3.4.2
tanglu 3.0: Python 3.4.2
tanglu 2.0: Python 3.4.1
torios 1.0: Python 3.4.2
trisquel 7.0: Python 3.4.0
ubports 15.04: Python 3.4.3
ubuntudp 15.04: Python 3.4.3
ubuntudp 14.04: Python 3.4.0
uhu 3: Python 3.4.1
ulteo 4.0.3: Python 3.4.0
univention 4.2-3: Python 3.4.2
untangle 13.1.0: Python 3.4.2
urix 7.0.3: Python 3.4.1
uruk 1.0: Python 3.4.0
vector 7.2: Python 3.4.3
vinux 5.1: Python 3.4.0
void current: Python 3.4.0
wattos r9: Python 3.4.0
whonix 13.0.0.1.1: Python 3.4.2
whonix 12.0.0.3.2: Python 3.4.2
wmlive 0.95.7-4: Python 3.4.2
zentyal 4.2: Python 3.4.0
zorin 11: Python 3.4.3
zorin 10: Python 3.4.3
====================================
137 distros with Python 3.4



3cx 9.2.1: Python 3.5.3
alt sisyphus: Python 3.5.4
alt 8.2: Python 3.5.1
alt 8.1: Python 3.5.1
antergos 2016.11.20: Python 3.5.2
antix 17: Python 3.5.3
apodio 11-beta0.2: Python 3.5.1
arya 2017: Python 3.5.2
avlinux 2017.4.9: Python 3.5.3
avlinux 2016.8.30: Python 3.5.1
backbox 5: Python 3.5.1
backslash kristoff: Python 3.5.1
berry 1.25: Python 3.5.4
berry 1.23: Python 3.5.1
biglinux 7.10: Python 3.5.3
blacklab 11.5: Python 3.5.2
blacklab 11.0.1: Python 3.5.1
blacklab 8.2: Python 3.5.1
blackarch 2016.12.29: Python 3.5.2
blackpanther 16.2: Python 3.5.1
blankon 10.0: Python 3.5.1
bluestar 4.8.4: Python 3.5.2
bodhi 4.4.0: Python 3.5.1
cae 2017-build4: Python 3.5.1
caine 9.0: Python 3.5.1
caine 8.0: Python 3.5.1
calculate 17.12: Python 3.5.4
chakra 2017.10: Python 3.5.2
chaletos 16.04.2: Python 3.5.1
chapeau 24: Python 3.5.1
debian unstable: Python 3.5.4
debian 9: Python 3.5.3
skolelinux 9: Python 3.5.3
deepin 15.5: Python 3.5.3
deepin 15.3: Python 3.5.1
devuan unstable: Python 3.5.4
devuan testing: Python 3.5.3
duzeru 3-alpha1: Python 3.5.3
elementary 0.4.1: Python 3.5.1
emmabuntus 9-1.01: Python 3.5.3
enso 0.2: Python 3.5.1
extix 16.5: Python 3.5.1
ferenos 2018.01: Python 3.5.2
ferenos 2017.10: Python 3.5.2
ferenos 2016.2: Python 3.5.1
freespire 3: Python 3.5.1
frugalware current: Python 3.5.4
frugalware 2.1: Python 3.5.2
funtoo current: Python 3.5.2
gentoo 20160514: Python 3.5.1
gnustep 2.5.1: Python 3.5.3
greenie 16.04.1: Python 3.5.1
grml 2017.05: Python 3.5.3
guixsd 0.13.0: Python 3.5.3
guixsd 0.12.0: Python 3.5.2
heads 0.3.1: Python 3.5.3
kali 2016.2: Python 3.5.1
kaos 2016.11: Python 3.5.2
karoshi 11.1: Python 3.5.1
kdeneon 20180201: Python 3.5.1
kdeneon 20171228: Python 3.5.1
knoppix 8.1: Python 3.5.3
knoppix 7.7.1: Python 3.5.1
korora 25: Python 3.5.2
korora 24: Python 3.5.1
kubuntu 17.04: Python 3.5.3
kubuntu 16.10: Python 3.5.1
linspire 7.0: Python 3.5.1
linuxfx 8.0.2: Python 3.5.1
lite 3.8: Python 3.5.1
liveraizo 9.18.01.14: Python 3.5.3
lliurex 16.06: Python 3.5.1
lubuntu 17.04: Python 3.5.3
lubuntu 16.10: Python 3.5.1
luninux 17.04: Python 3.5.3
luninux 16.04: Python 3.5.1
luninux 15.10: Python 3.5.0
lxle 16.04.3: Python 3.5.1
mageia 6: Python 3.5.3
makulu 14: Python 3.5.1
mangaka cho: Python 3.5.1
manjaro 16.10.3: Python 3.5.2
maui 17.06: Python 3.5.2
maui 2.1: Python 3.5.1
maui 1: Python 3.5.1
max 9.0: Python 3.5.1
metamorphose 8.5.7: Python 3.5.1
metamorphose 8.0.4: Python 3.5.1
mint 18.3: Python 3.5.2
mx 17: Python 3.5.3
netrunner 17.10: Python 3.5.3
nixos 17.09: Python 3.5.4
nixos 16.09: Python 3.5.2
nixos 16.03: Python 3.5.1
nst 24-7977: Python 3.5.1
ob2d 2017-1.2: Python 3.5.3
openbsd 6.1: Python 3.5.2
openbsd 6.0: Python 3.5.2
osgeo 11.0: Python 3.5.1
osgeo 10.5: Python 3.5.1
pardus 17.1: Python 3.5.3
pardustopluluk 4.1: Python 3.5.1
parrotsecurity 3.7: Python 3.5.3
parrotsecurity 3.0.1: Python 3.5.1
peachosi 16.04: Python 3.5.1
pearl 5.0: Python 3.5.2
pearl 4.0: Python 3.5.1
peppermint 8: Python 3.5.1
peppermint 7: Python 3.5.1
porteus 3.2.2: Python 3.5.2
primtux 3: Python 3.5.3
proxmox 5.1: Python 3.5.3
pureos 8.0-beta1: Python 3.5.3
q4os 2.4: Python 3.5.3
qubes 4.0-rc3: Python 3.5.4
raspbian 2017-11-29: Python 3.5.3
rds 10.0: Python 3.5.3
rebeccablackos 2016-02-08: Python 3.5.1
rebellin 3.5: Python 3.5.1
rebellin 3.0: Python 3.5.1
redcore 1801: Python 3.5.4
rosa r10: Python 3.5.2
rosa r9: Python 3.5.2
rss 10.0: Python 3.5.3
runtu 16.04.3: Python 3.5.1
sabayon 18.02: Python 3.5.4
sabayon 17.12: Python 3.5.4
salentos 2.0: Python 3.5.3
sharklinux 4.13.0: Python 3.5.1
siduction 17.1.0: Python 3.5.3
siduction 16.1.0: Python 3.5.1
solus 3: Python 3.5.4
solus 2017.04.18.0: Python 3.5.2
solus 1.2.1: Python 3.5.2
solydxk 201801: Python 3.5.3
solydxk 9: Python 3.5.3
sparky 4.7: Python 3.5.3
sparky 4.5.2: Python 3.5.1
subgraph 2017-09-22-alpha: Python 3.5.3
systemrescue 5.1.2: Python 3.5.4
tails 3.5: Python 3.5.3
tanglu 4.0: Python 3.5.1
trisquel 8.0-alpha: Python 3.5.1
tuxtrans 16.04: Python 3.5.1
ubuntu 17.04: Python 3.5.3
ubuntubudgie 17.04: Python 3.5.3
ubuntubudgie 16.10: Python 3.5.1
ubuntudp 16.04.1: Python 3.5.1
ubuntukylin 17.04: Python 3.5.3
ubuntukylin 16.10: Python 3.5.1
ubuntumate 17.04: Python 3.5.3
ubuntumate 16.10: Python 3.5.1
ubuntustudio 17.04: Python 3.5.3
ubuntustudio 16.10: Python 3.5.1
ultimate 5.1: Python 3.5.1
ultimate 5.0.1: Python 3.5.1
uruk 2.0: Python 3.5.1
ututo 2017-rc: Python 3.5.1
voyager 9: Python 3.5.3
voyager 16.04.3: Python 3.5.1
wattos r10: Python 3.5.1
wifislax 4.12: Python 3.5.2
xubuntu 17.04: Python 3.5.3
xubuntu 16.10: Python 3.5.1
zentyal 5.0: Python 3.5.1
zorin 12.2: Python 3.5.1
====================================
166 distros with Python 3.5



absolute 15.0-beta3: Python 3.6.4
antergos 18.2: Python 3.6.4
antergos 17.12: Python 3.6.3
arch current: Python 3.6.4
archlabs 2017.12: Python 3.6.3
archlabs 5.0: Python 3.6.1
archman 2018.02: Python 3.6.4
artix 2018.01.05: Python 3.6.4
artix 2017.08.08: Python 3.6.2
berry 1.26: Python 3.6.3
blackarch 2017.12.11: Python 3.6.3
bluestar 4.14.15: Python 3.6.4
bluestar 4.14.3: Python 3.6.3
cucumber 1.0: Python 3.6.0
debian unstable: Python 3.6.4
debian testing: Python 3.6.4
devuan unstable: Python 3.6.4
extix 18.2: Python 3.6.3
extix 17.8: Python 3.6.3
fedora rawhide: Python 3.6.4
fedora 27: Python 3.6.2
fedora 26: Python 3.6.1
funtoo current: Python 3.6.0
gentoo unstable: Python 3.6.4
gentoo stable: Python 3.6.3
kali 2018.1: Python 3.6.4
kali 2017.3: Python 3.6.3
kaos 2018.01: Python 3.6.4
kaos 2017.11: Python 3.6.3
korora 26: Python 3.6.2
kubuntu 17.10: Python 3.6.3
lfs 8.1-blfs: Python 3.6.2
lubuntu 17.10: Python 3.6.3
mageia cauldron: Python 3.6.2
manjaro stable: Python 3.6.4
manjaro 17.1.4: Python 3.6.4
nitrux 1.0.8: Python 3.6.4
nixos 17.09: Python 3.6.2
nixos 16.09: Python 3.6.0
nst 26-9267: Python 3.6.2
nutyx packages: Python 3.6.3
nutyx 10.0: Python 3.6.3
nutyx 9.1: Python 3.6.2
openbsd 6.2: Python 3.6.2
openbsd 6.1: Python 3.6.0
opensuse tumbleweed: Python 3.6.4
parabola 2017.11.05: Python 3.6.3
parrotsecurity 3.11: Python 3.6.4
parrotsecurity 3.7: Python 3.6.2
pisi 2.0-rc: Python 3.6.0
popos 17.10: Python 3.6.3
q4os 3.1-testing: Python 3.6.4
runtu 18.04-alpha: Python 3.6.3
siduction 18.1.0: Python 3.6.4
slackware current: Python 3.6.4
sparky 5.2: Python 3.6.3
sle 15-beta1: Python 3.6.2
swagarch 18.02: Python 3.6.4
swagarch 17.12: Python 3.6.3
systemrescue 5.2.0: Python 3.6.3
ubuntu snapshot: Python 3.6.4
ubuntu 17.10: Python 3.6.3
ubuntubudgie 17.10: Python 3.6.3
ubuntukylin 17.10: Python 3.6.3
ubuntumate 17.10: Python 3.6.3
ubuntustudio 17.10: Python 3.6.3
ultimate 5.7: Python 3.6.3
void current: Python 3.6.4
voyager 18.04-alpha: Python 3.6.3
xubuntu 17.10: Python 3.6.3
zenwalk current: Python 3.6.3
====================================
71 distros with Python 3.6



debian unstable: Python 3.7.0
debian testing: Python 3.7.0
devuan unstable: Python 3.7.0
====================================
3 distros with Python 3.7
```

**Comment by cclauss** [comment]
Fascinating...  Is there a way to tell:
1. Which distros have Python 3 as the _default_ Python out-of-the-box?  $ __python --version__ --> _Py3_
2. Which distros no longer have Py2 installed out-of-the-box?  $ __python2__ --> _command not found_

**Comment by Mariatta** [comment]
Thanks for the update!
I think there should be a better way to keep track of the output, and not in Readme.
I don't know where yet though, ideas? I'm inclined not to add the output to readme.

I'll keep it open so interested folks can find it :)

**Comment by Mariatta** [comment]
> Is there a way to tell:
> 
> Which distros have Python 3 as the default Python out-of-the-box? $ python --version --> Py3
> Which distros no longer have Py2 installed out-of-the-box? $ python2 --> command not found
> 

Interesting questions!! I'd like to find out too!
Not sure how yet..

**Comment by cclauss** [comment]
A cleaner solution would be to put the output in a separate __output.md__ file and then link to it from README.md.

**Comment by Mariatta** [comment]
Sure. Let's go with `.rst` instead of `.md`.

**Comment by Mariatta** [comment]
@hugovk I think this needs rebase with master. Will you be able to do that?
I can merge it afterwards. Thanks.

**Comment by hugovk** [comment]
Rebased! Moved! Updated!

Current full output is:
```console
[hugo:/tmp/python_versions_and_distros] patch-1(+1/-1) 3s ± python3 -m py_versions_and_distros
abuledu 15.08-beta: Python 3.4.0
antix 16.3: Python 3.4.2
antix 15: Python 3.4.2
apodio 10.03: Python 3.4.0
avlinux 2017.4.9: Python 3.4.4
avlinux 2016.8.30: Python 3.4.4
backbox 4.7: Python 3.4.0
bicom 5.0.0: Python 3.4.3
bicom 4.1.2-r2: Python 3.4.3
biolinux 8.0.8: Python 3.4.0
bitkey 14.2.0: Python 3.4.2
blackarch 2015.03.29: Python 3.4.3
boss 6.1: Python 3.4.2
bunsenlabs 20170429: Python 3.4.2
bunsenlabs 20160710: Python 3.4.2
caine 7.0: Python 3.4.0
calculate 15.17: Python 3.4.3
calculate 14.16.2: Python 3.4.1
canaima 5.1: Python 3.4.2
chakra 2016.02: Python 3.4.3
chakra 2015.11: Python 3.4.3
chaletos 14.04.3: Python 3.4.0
debian unstable: Python 3.4.2
skolelinux 8: Python 3.4.2
deepin 2014.3: Python 3.4.0
deft 2017.1: Python 3.4.0
devuan 1.0.0: Python 3.4.2
duzeru 2.4: Python 3.4.2
easynas 0.6.2: Python 3.4.1
edubuntu 14.04: Python 3.4.0
elementary 0.3.2: Python 3.4.3
emmabuntus 8-1.03: Python 3.4.2
emmabuntus 3-1.04: Python 3.4.0
funtoo current: Python 3.4.6
gecko 423: Python 3.4.6
gecko 422: Python 3.4.5
gentoo 20160514: Python 3.4.3
greenie 14.04.5: Python 3.4.0
grml 2014.11: Python 3.4.2
guixsd 0.12.0: Python 3.4.5
guixsd 0.9.0: Python 3.4.3
karoshi 10.1.2: Python 3.4.0
knoppix 7.6.1: Python 3.4.3
kodachi 3.7: Python 3.4.2
kxstudio 14.04.5: Python 3.4.0
linuxfx 7.4.2: Python 3.4.0
lite 2.8: Python 3.4.0
lliurex 15.05: Python 3.4.0
luninux 15.10: Python 3.4.3
lxle 14.04.4: Python 3.4.0
mageia 5.1: Python 3.4.3
makulu 10: Python 3.4.3
makulu 7.0: Python 3.4.0
mangaka cho: Python 3.4.4
mangaka mou: Python 3.4.0
max 8.0: Python 3.4.0
metamorphose 7.1.8: Python 3.4.2
minino 2017: Python 3.4.1
minino 3.0: Python 3.4.2
mint 17.3: Python 3.4.3
mx 16.1: Python 3.4.2
netrunner 16: Python 3.4.3
nixos 17.09: Python 3.4.7
nixos 16.09: Python 3.4.5
nixos 16.03: Python 3.4.4
nst 22-7334: Python 3.4.2
ob2d 1.0.0: Python 3.4.2
openbsd 6.1: Python 3.4.5
openbsd 6.0: Python 3.4.5
openmandriva 3.03: Python 3.4.4
openmediavault 3.0.94: Python 3.4.2
opensuse 42.3: Python 3.4.6
opensuse 42.2: Python 3.4.5
pardustopluluk 3.0: Python 3.4.2
parrotsecurity 3.0.1: Python 3.4.4
pclinuxos apt: Python 3.4.3
pclinuxos 2017.11: Python 3.4.3
pclinuxos 2016.03: Python 3.4.3
peachosi 14.04.01.36: Python 3.4.0
pelicanhpc 4.1: Python 3.4.2
pentoo 2015.0-rc5: Python 3.4.3
peppermint 6: Python 3.4.0
pinguy 14.04.5: Python 3.4.3
pisi 1.2: Python 3.4.1
pisi 1.1: Python 3.4.1
point 3.2: Python 3.4.2
primtux 2: Python 3.4.2
primtux eiffel: Python 3.4.2
proxmox 4.4: Python 3.4.2
q4os 1.8.8: Python 3.4.2
qubes 3.2: Python 3.4.3
raspbian 2017-07-05: Python 3.4.2
redcore 1710: Python 3.4.5
refracta 8.3-20170305: Python 3.4.2
rescatux 0.51-beta3: Python 3.4.2
robolinux 8.10: Python 3.4.2
robolinux 8.8.1: Python 3.4.2
rosa r8: Python 3.4.5
runtu 14.04.2: Python 3.4.0
sabayon 16.11: Python 3.4.3
salentos 1.0.1: Python 3.4.2
salentos 14.04.2: Python 3.4.0
solydxk 201701: Python 3.4.2
star 1.0.2: Python 3.4.2
steamos 2.148: Python 3.4.2
steamos 2.117: Python 3.4.2
sle 12-sp3: Python 3.4.6
swecha 2016: Python 3.4.0
swift 16: Python 3.4.2
systemrescue 4.9.0: Python 3.4.3
tails 2.12: Python 3.4.2
tanglu 3.0: Python 3.4.2
tanglu 2.0: Python 3.4.1
torios 1.0: Python 3.4.2
trisquel 7.0: Python 3.4.0
ubports 15.04: Python 3.4.3
ubuntudp 15.04: Python 3.4.3
ubuntudp 14.04: Python 3.4.0
uhu 3: Python 3.4.1
ulteo 4.0.3: Python 3.4.0
untangle 13.1.0: Python 3.4.2
urix 7.0.3: Python 3.4.1
uruk 1.0: Python 3.4.0
vector 7.2: Python 3.4.3
vinux 5.1: Python 3.4.0
void current: Python 3.4.0
wattos r9: Python 3.4.0
whonix 13.0.0.1.1: Python 3.4.2
whonix 12.0.0.3.2: Python 3.4.2
wmlive 0.95.7-4: Python 3.4.2
zentyal 4.2: Python 3.4.0
zorin 11: Python 3.4.3
zorin 10: Python 3.4.3
====================================
133 distros with Python 3.4



3cx 9.2.1: Python 3.5.3
alt sisyphus: Python 3.5.4
alt 8.2: Python 3.5.1
alt 8.1: Python 3.5.1
antergos 2016.11.20: Python 3.5.2
antix 17.1: Python 3.5.3
apodio 11-beta0.2: Python 3.5.1
arya 2017: Python 3.5.2
avlinux 2017.4.9: Python 3.5.3
avlinux 2016.8.30: Python 3.5.1
backbox 5: Python 3.5.1
backslash kristoff: Python 3.5.1
berry 1.25: Python 3.5.4
berry 1.23: Python 3.5.1
biglinux 7.10: Python 3.5.3
blacklab 11.6: Python 3.5.2
blacklab 11.0.1: Python 3.5.1
blacklab 8.2: Python 3.5.1
blackarch 2016.12.29: Python 3.5.2
blackpanther 16.2: Python 3.5.1
blankon 10.0: Python 3.5.1
bluestar 4.8.4: Python 3.5.2
bodhi 4.5.0: Python 3.5.2
cae 2017-build4: Python 3.5.1
caine 9.0: Python 3.5.1
caine 8.0: Python 3.5.1
calculate 17.12.2: Python 3.5.4
canaima 6.0-alfa: Python 3.5.3
chakra 2017.10: Python 3.5.2
chaletos 16.04.2: Python 3.5.1
debian unstable: Python 3.5.5
debian 9: Python 3.5.3
skolelinux 9: Python 3.5.3
deepin 15.5: Python 3.5.3
deepin 15.3: Python 3.5.1
devuan unstable: Python 3.5.4
devuan testing: Python 3.5.3
duzeru 3-alpha1: Python 3.5.3
elastix 5.0.0: Python 3.5.3
elementary 0.4.1: Python 3.5.1
emmabuntus 9-1.01: Python 3.5.3
enso 0.2: Python 3.5.1
extix 16.5: Python 3.5.1
ferenos 2018.01: Python 3.5.2
ferenos 2017.10: Python 3.5.2
ferenos 2016.2: Python 3.5.1
freespire 3.0.8: Python 3.5.1
frugalware 2.1: Python 3.5.2
gentoo 20160514: Python 3.5.1
gnustep 2.5.1: Python 3.5.3
greenie 16.04.1: Python 3.5.1
grml 2017.05: Python 3.5.3
guixsd 0.13.0: Python 3.5.3
guixsd 0.12.0: Python 3.5.2
heads 0.3.1: Python 3.5.3
kali 2016.2: Python 3.5.1
kaos 2016.11: Python 3.5.2
karoshi 11.1: Python 3.5.1
kdeneon 20180301: Python 3.5.1
kdeneon 20171228: Python 3.5.1
knoppix 8.1: Python 3.5.3
knoppix 7.7.1: Python 3.5.1
korora 25: Python 3.5.2
korora 24: Python 3.5.1
kubuntu 17.04: Python 3.5.3
linspire 7.0: Python 3.5.1
linuxfx 8.0.2: Python 3.5.1
lite 3.8: Python 3.5.1
lliurex 16.06: Python 3.5.1
lubuntu 17.04: Python 3.5.3
lubuntu 16.10: Python 3.5.1
luninux 17.04: Python 3.5.3
luninux 16.04: Python 3.5.1
luninux 15.10: Python 3.5.0
lxle 16.04.3: Python 3.5.1
mageia 6: Python 3.5.3
makulu 14: Python 3.5.1
mangaka cho: Python 3.5.1
manjaro 16.10.3: Python 3.5.2
maui 17.06: Python 3.5.2
maui 2.1: Python 3.5.1
maui 1: Python 3.5.1
max 9.0: Python 3.5.1
metamorphose 8.5.7: Python 3.5.1
metamorphose 8.0.4: Python 3.5.1
mint 18.3: Python 3.5.2
mx 17.1: Python 3.5.3
neptune 5.0: Python 3.5.3
netrunner 17.10: Python 3.5.3
nixos 17.09: Python 3.5.4
nixos 16.09: Python 3.5.2
nixos 16.03: Python 3.5.1
nst 24-7977: Python 3.5.1
ob2d 2017-1.2: Python 3.5.3
openbsd 6.1: Python 3.5.2
openbsd 6.0: Python 3.5.2
osgeo 11.0: Python 3.5.1
osgeo 10.5: Python 3.5.1
pardus 17.2: Python 3.5.3
pardustopluluk 4.1: Python 3.5.1
parrotsecurity 3.7: Python 3.5.3
parrotsecurity 3.0.1: Python 3.5.1
peachosi 16.04: Python 3.5.1
pearl 5.0: Python 3.5.2
pearl 4.0: Python 3.5.1
peppermint 8: Python 3.5.1
peppermint 7: Python 3.5.1
porteus 3.2.2: Python 3.5.2
primtux 3: Python 3.5.3
proxmox 5.1: Python 3.5.3
pureos 8.0-beta1: Python 3.5.3
q4os 2.4: Python 3.5.3
qubes 4.0-rc5: Python 3.5.4
raspbian 2018-03-13: Python 3.5.3
rds 10.0: Python 3.5.3
rebeccablackos 2018-01-14: Python 3.5.3
rebeccablackos 2016-02-08: Python 3.5.1
rebellin 3.5: Python 3.5.1
rebellin 3.0: Python 3.5.1
redcore 1801: Python 3.5.4
robolinux 9.1: Python 3.5.1
rosa r10: Python 3.5.2
rosa r9: Python 3.5.2
rss 10.0: Python 3.5.3
runtu 16.04.3: Python 3.5.1
sabayon 18.03: Python 3.5.4
sabayon 17.12: Python 3.5.4
salentos 2.0: Python 3.5.3
sharklinux 4.13.0: Python 3.5.1
siduction 17.1.0: Python 3.5.3
siduction 16.1.0: Python 3.5.1
solus 3: Python 3.5.4
solus 2017.04.18.0: Python 3.5.2
solus 1.2.1: Python 3.5.2
solydxk 201801: Python 3.5.3
solydxk 9: Python 3.5.3
sparky 4.7: Python 3.5.3
sparky 4.5.2: Python 3.5.1
subgraph 2017-09-22-alpha: Python 3.5.3
systemrescue 5.1.2: Python 3.5.4
tails 3.6.1: Python 3.5.3
tanglu 4.0: Python 3.5.1
trisquel 8.0-alpha: Python 3.5.1
tuxtrans 16.04: Python 3.5.1
ubuntu 17.04: Python 3.5.3
ubuntubudgie 17.04: Python 3.5.3
ubuntudp 16.04.1: Python 3.5.1
ubuntukylin 17.04: Python 3.5.3
ubuntumate 17.04: Python 3.5.3
ubuntustudio 17.04: Python 3.5.3
ubuntustudio 16.10: Python 3.5.1
ultimate 5.1: Python 3.5.1
ultimate 5.0.1: Python 3.5.1
univention 4.3-0: Python 3.5.3
uruk 2.0: Python 3.5.1
ututo 2017-rc: Python 3.5.1
voyager 9: Python 3.5.3
voyager 16.04.3: Python 3.5.1
wattos r10: Python 3.5.1
wifislax 4.12: Python 3.5.2
xubuntu 17.04: Python 3.5.3
zentyal 5.0: Python 3.5.1
zevenet 5.0: Python 3.5.3
zorin 12.3: Python 3.5.1
====================================
164 distros with Python 3.5



absolute 15.0-beta4: Python 3.6.4
antergos 18.3: Python 3.6.4
antergos 17.12: Python 3.6.3
arch current: Python 3.6.4
archlabs 2018.03: Python 3.6.4
archlabs 2017.12: Python 3.6.3
archlabs 5.0: Python 3.6.1
archman 2018.03: Python 3.6.4
artix 2018.01.05: Python 3.6.4
artix 2017.08.08: Python 3.6.2
berry 1.26: Python 3.6.3
blackarch 2017.12.11: Python 3.6.3
bluestar 4.15.8: Python 3.6.4
bluestar 4.14.3: Python 3.6.3
cucumber 1.0: Python 3.6.0
debian unstable: Python 3.6.4
debian testing: Python 3.6.4
devuan unstable: Python 3.6.4
extix 18.2: Python 3.6.3
extix 17.8: Python 3.6.3
fedora rawhide: Python 3.6.4
fedora 27: Python 3.6.2
fedora 26: Python 3.6.1
frugalware current: Python 3.6.4
gentoo unstable: Python 3.6.4
gentoo stable: Python 3.6.3
gparted 0.31.0-1: Python 3.6.5
kali 2018.1: Python 3.6.4
kali 2017.3: Python 3.6.3
kaos 2018.03: Python 3.6.4
kaos 2017.11: Python 3.6.3
korora 26: Python 3.6.2
kubuntu 18.04-beta1: Python 3.6.4
kubuntu 17.10: Python 3.6.3
lubuntu 17.10: Python 3.6.3
mageia cauldron: Python 3.6.4
manjaro stable: Python 3.6.4
manjaro 17.1.5: Python 3.6.4
netrunner 18.03: Python 3.6.4
nitrux 1.0.9: Python 3.6.4
nixos 17.09: Python 3.6.2
nixos 16.09: Python 3.6.0
nst 26-9267: Python 3.6.2
nutyx packages: Python 3.6.4
nutyx 10.1: Python 3.6.4
nutyx 9.1: Python 3.6.2
openbsd 6.2: Python 3.6.2
openbsd 6.1: Python 3.6.0
opensuse tumbleweed: Python 3.6.4
parabola 2017.11.05: Python 3.6.3
parrotsecurity 3.11: Python 3.6.4
parrotsecurity 3.7: Python 3.6.2
pisi 2.0-rc: Python 3.6.0
popos 17.10: Python 3.6.3
porteus 4.0-rc4: Python 3.6.4
q4os 3.1-testing: Python 3.6.4
runtu 18.04-alpha: Python 3.6.3
siduction 18.2.0: Python 3.6.4
slackware current: Python 3.6.4
sparky 5.3: Python 3.6.4
sle 15-beta1: Python 3.6.2
swagarch 18.03: Python 3.6.4
swagarch 17.12: Python 3.6.3
systemrescue 5.2.1: Python 3.6.3
ubuntu snapshot: Python 3.6.5
ubuntu 17.10: Python 3.6.3
ubuntubudgie 18.04-beta1: Python 3.6.4
ubuntubudgie 17.10: Python 3.6.3
ubuntukylin 18.04-beta1: Python 3.6.4
ubuntukylin 17.10: Python 3.6.3
ubuntumate 18.04-beta1: Python 3.6.4
ubuntumate 17.10: Python 3.6.3
ubuntustudio 17.10: Python 3.6.3
ultimate 5.7: Python 3.6.3
void current: Python 3.6.4
voyager 18.04-alpha2: Python 3.6.4
xubuntu 18.04-beta1: Python 3.6.4
xubuntu 17.10: Python 3.6.3
zenwalk current: Python 3.6.4
====================================
79 distros with Python 3.6



debian unstable: Python 3.7.0
debian testing: Python 3.7.0
devuan unstable: Python 3.7.0
====================================
3 distros with Python 3.7



⌂63% [hugo:/tmp/python_versions_and_distros] patch-1(+1/-1) 8m42s ±
```

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Awesome! Thanks @hugovk!

**Pull request merged**
