### PR TITLE
Add user agent

### LINKED ISSUE #7: Not working: AttributeError: 'NoneType' object has no attribute 'find_all'
I get identical results locally and in Travis CI...
* https://travis-ci.org/Mariatta/python_versions_and_distros/builds/338503075#L478-L490

@hugovk

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #7.

### CODE REVIEW

**Comment by hugovk** [comment]
The test run is timing out on the CI, but it's working locally.

I'll remove it from the CI. Another solution could be to add some command-line arguments so it only tries to fetch a smaller amount of data.

**Comment by cclauss** [comment]
travis_wait did not help either.  It is NOT working for me locally.  If it is working for you then would you please update the README with the output of a current run?

**Comment by hugovk** [comment]
Sure, see https://github.com/Mariatta/python_versions_and_distros/pull/9.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks! Confirmed that it works locally.

**Pull request merged**
